name: qrty
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  image_picker: ^1.2.1
  objectbox: ^5.0.3
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  objectbox_generator: ^5.0.3

objectbox:

  # Or optionally specify the lib and test output folder separately.
  output_dir:
    lib: core/storage/

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/


fonts:
  - family: Itim
    fonts:
      - asset: fonts/Itim/Itim-Regular.ttf
        style: Regular
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

